//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2JamLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2JamLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dinput {
            get {
                object obj = ResourceManager.GetObject("dinput", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WINDOWMODE]
        ///UseWindowMode=1
        ///UseGDI=0
        ///UseDirect3D=1
        ///UseDirectInput=1
        ///UseDirectDraw=1
        ///UseDDrawColorEmulate=1
        ///UseDDrawFlipBlt=1
        ///UseDDrawColorConvert=1
        ///UseDDrawPrimaryBlt=1
        ///UseDDrawAutoBlt=0
        ///UseDDrawEmulate=0
        ///UseDDrawPrimaryLost=0
        ///UseCursorMsg=1
        ///UseCursorSet=1
        ///UseCursorGet=1
        ///UseSpeedHack=1
        ///SpeedHackMultiple=10
        ///UseBackgroundResize=0
        ///UseForegroundControl=1
        ///UseFGCGetActiveWindow=1
        ///UseFGCGetForegroundWindow=1
        ///UseFGCFixedWindowPosition=1
        ///EnableExtraKey=0
        ///ShowFps=1
        ///UseCursorClip=1
        ///UseBackground [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monoxjam {
            get {
                return ResourceManager.GetString("monoxjam", resourceCulture);
            }
        }
    }
}
